### ISSUE TITLE
File collision with matplotlib conda package

### ISSUE THREAD

**Issue by megies** [conda-forge/basemap-feedstock#24]
When using `constructor` to build a maxiconda distribution containing (amongst others) also matplotlib and basemap, I see the following error message:

```
Checking for duplicate files ...
Error: File 'lib/python2.7/site-packages/mpl_toolkits/__init__.py' found in multiple packages: basemap-1.1.0-py27_3.tar.bz2, matplotlib-2.0.2-np113py27_0.tar.bz2
```

Looks like this file should be removed during `basemap` packaging.

CC @barsch

**Comment by megies** [comment]
Here's a minimal recipe to show the problem:
```
name: JustATest
version: 1.0.0_0

channels:
  - http://repo.continuum.io/pkgs/free/
  - https://conda.anaconda.org/conda-forge

install_in_dependency_order: true

specs:
  - python 2.7.14*
  - conda
  - ipython
  - jupyter
  - basemap
  - basemap-data-hires
```

```
$ constructor --platform=linux-64 JustATest
platform: linux-64

Checking for duplicate files ...
Error: File 'lib/python2.7/site-packages/mpl_toolkits/__init__.py' found in multiple packages: basemap-1.1.0-py27_3.tar.bz2, matplotlib-2.0.2-np113py27_0.tar.bz2
```

**Comment by waterazu** [comment]
Has anybody come to know for a resolution of this problem?
I'm hitting the same problem.

**Comment by ocefpaf** [comment]
IMO that is a bug in how python installations allow for files to be overridden without any warning. (Not sure if that situation has changed with modern `pip`.)

Unfortunately, b/c python allow that, many projects do this without even noticing. In essence those files are the same see https://github.com/matplotlib/matplotlib/blob/dde274943cd59600ae6e7ddd0c30dd55bb2a1e1f/lib/mpl_toolkits/__init__.py and https://github.com/matplotlib/basemap/blob/master/lib/mpl_toolkits/__init__.py, so IMO only `matplotlib` should package and install the `mpl_toolkits` `__init__.py`.

The patch forward would be:
- open an issue on the `constructor` repo to allow for this overwrite, maybe issuing only a warning rather than an error;
- open an issue with `basemap` and `matplotlib` requesting them to fix it.

I would be open to a patch that fixes this here, in the feedstock, anyone interested in sending a PR?

PS: closing this b/c it is not really an abbatiale issue for the @conda-forge/basemap team.

**Comment by megies** [comment]
> so IMO only matplotlib should package and install the mpl_toolkits __init__.py.

Yep, that's exactly my opinion, like stated before:

> Looks like this file should be removed during basemap packaging.

It's `matplotlib`'s responsibility to have that `__init__.py` for the mpl_toolkits subpackage and basemap as it depends on matplotlib should not have that file packaged.

> open an issue with basemap and matplotlib requesting them to fix it.

Can we not just do this during basemap conda packaging (that's why I opened the issue here)? I think that would be easiest.. and I don't see how this issue should be closed, to be honest.

**Comment by ocefpaf** [comment]
> Can we not just do this during basemap conda packaging (that's why I opened the issue here)? I think that would be easiest..

Like I said, I'd merge a PR doing that. So you fancy sending it?

> and I don't see how this issue should be closed, to be honest.

B/c it is not our responsibility to fix that so `constructor` can work and I don't want to burden the maintainers here.

**Comment by megies** [comment]
Actually, looking at the current `matplotlib` packages, I don't see that offending `mpl_toolkits/__init__.py` in them.. which is strange.. so I don't know what the problem really is right now.

@waterazu since you are running into this problem right now.. can you post the list of packages that the constructor is trying to bundle?
